name: Build WLAN Pi Kernel for Debian Bookworm

# Description: This workflow builds the WLAN Pi custom Linux kernel and packages it into a Debian package tailored for Debian Bookworm.

on:
  push:
    branches:
      - add-build-action  # Trigger build on pushes to 'add-build-action' branch
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to build from'
        required: true
        default: 'add-build-action'
        type: choice
        options:
          - add-build-action
          - main
          - develop
          - feature-branch-1
          - feature-branch-2
          # Add more branches as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    env:
      DISTRO: bookworm
      VERSION_CODENAME: bookworm
      KERNEL_TARGET_DISTRO: Debian
      KERNEL_TARGET_VERSION: bookworm

    steps:
      # Step 1: Checkout the repository with the selected branch
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # Step 2: Install Dependencies for Bookworm
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libncurses-dev flex bison libssl-dev \
              bc libelf-dev libudev-dev libpci-dev libiberty-dev autoconf automake libtool \
              libpython3-dev crossbuild-essential-arm64 dpkg-dev

      # Step 3: Make the build script executable
      - name: Make Build Script Executable
        run: chmod +x build/build-wlanpi-kernel.sh

      # Step 4: Execute the build script for Bookworm
      - name: Execute Build Script
        run: ./build/build-wlanpi-kernel.sh

      # Step 5: Upload the built Debian package as an artifact
      - name: Upload Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: wlanpi-kernel-deb-${{ env.DISTRO }}-${{ github.event.inputs.branch }}
          path: output/*.deb

