name: Build WLAN Pi Kernel for Debian Bookworm

# Description: This workflow builds the WLAN Pi custom Linux kernel and packages it into a Debian package tailored for Debian Bookworm.

on:
  push:
    branches:
      - 6.12-bookworm  # Updated to trigger on '6.12-bookworm' branch
  workflow_dispatch:    # Enables manual triggering without inputs

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    env:
      DISTRO: bookworm
      VERSION_CODENAME: bookworm
      KERNEL_TARGET_DISTRO: Debian
      KERNEL_TARGET_VERSION: bookworm

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # By default, actions/checkout checks out the branch where the workflow is triggered
          fetch-depth: 0  # Optional: Fetch all history for all branches and tags

      # Step 2: Install Dependencies for Bookworm
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libncurses-dev flex bison libssl-dev \
              bc libelf-dev libudev-dev libpci-dev libiberty-dev autoconf automake libtool \
              libpython3-dev crossbuild-essential-arm64 dpkg-dev

      # Step 3: Make the build script executable
      - name: Make Build Script Executable
        run: chmod +x build/build-wlanpi-kernel.sh

      # Step 4: Execute the build script for Bookworm
      - name: Execute Build Script
        run: ./build/build-wlanpi-kernel.sh

      # Step 5: Upload the built Debian package as an artifact
      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: wlanpi-kernel-deb-bookworm
          path: output/*.deb
